version: "3.6"
services:
  mongo:
    image: mongo:3.4.9
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./tmp/mongo:/etc/mongo
  
  # scraper:
  #   env_file: .env
  #   image: alextanhongpin/go-github-scraper:1.0.0
  #   ports:
  #     - 127.0.0.1:8080:8080
  #   environment:
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #     DB_NAME: ${DB_NAME}
  #     DB_AUTH: ${DB_AUTH}
  #     DB_HOST: mongo
  #     GITHUB_TOKEN: ${GITHUB_TOKEN}
