version: "3.6"
services:
  mongo:
    image: mongo:3.4.9
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./tmp/mongo:/etc/mongo